project:
  type: book


bibliography: references.bib


book:
  title: "Linguistics with Worked Computational Examples"
  description: "A book about using Python and R to analyze linguistic data."
  repo-url: https://github.com/michaelbennieUFL/Smackademia-Computational-Linguistics
  repo-branch: Master
  repo-actions: [ edit, issue ]
  repo-subdir: "docs"
  chapters:
    - index.qmd
    - part: getting_started/installation.qmd
      chapters:
        - getting_started/editor.qmd
        - getting_started/packages.qmd
        - getting_started/plotting.qmd
    - part: exercises/exercises.qmd
      chapters:
        - exercises/grading.qmd
        - exercises/gradethis.qmd
        - exercises/environments.qmd
    - part: interactive/reactivity.qmd
      chapters:
        - interactive/data.qmd
        - interactive/dynamic.qmd
        - interactive/hybrid.qmd
        - interactive/dashboards.qmd
    - part: other/tables.qmd
      chapters:
        - other/resources.qmd
        - other/htmlwidgets.qmd
        - other/py_output.qmd
        - other/slides.qmd
    - reference/references.qmd

format:
  live-html:
    theme:
      light: cosmo
      dark: darkly
