project:
  type: book


bibliography: references.bib


book:
  title: "Linguistics with Worked Computational Examples"
  description: "A book about using Python and R to analyze linguistic data."
  repo-url: https://github.com/michaelbennieUFL/Smackademia-Computational-Linguistics
  repo-branch: Master
  repo-actions: [ edit, issue ]
  repo-subdir: "docs"
  chapters:
    - index.qmd
    - part: zipfs_law/overview.qmd
      chapters:
        - zipfs_law/fundamentals.qmd
        - zipfs_law/analyzing_corpora.qmd
        - zipfs_law/exercises.qmd
    - reference/references.qmd

format:
  live-html:
    theme:
      light: cosmo
      dark: darkly
